version: '3'
services:
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    container_name: "gocrawler-redis"

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        discovery-type: "single-node"
    ports:
      - "9200:9200"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    container_name: "gocrawler-es7"